SpeedStorm:
  cooldown: 60
  dragonEggFactor: 0.5
  attackSpeed: 4.0
  speedAmplifier: 3
  duration: 12
Dash:
  cooldown: 5  # Cooldown in Sekunden
Rewind:
  cooldown: 30  # Cooldown in Sekunden
BloodRush:
  cooldown: 60
Stun:
  cooldown: 60
  duration: 3   # in Sekunden
Lightning:
  cooldown: 40       # Sekunden
  duration: 5        # Sekunden aktive Zeit
  range: 10          # Radius um den Spieler
Magma:
  cooldown: 30     # Cooldown in Sekunden für Verdampfen
  radius: 5        # Radius für Wasser-Verdunstung
Healer:
  cooldown: 45   # Cooldown in Sekunden
  radius: 5      # Radius des Heilkreises
  duration: 10   # Dauer der Heilung in Sekunden
soulsplit:
  duration: 5     # Dauer in Sekunden
  cooldown: 120    # Cooldown in Sekunden
emerald:
  cooldown: 100          # Cooldown in Sekunden
  debuff_duration: 5    # Dauer des Verfluchens (in Sekunden)
  fail_chance: 0.3      # 30% Chance dass Items fehlschlagen
invis:
  cooldown: 60        # Cooldown in Sekunden
  duration: 20        # Dauer der Aktivierung (Sekunden)
  blind_radius: 4     # Radius für Blindheit-Effekt
domain:
  cooldown: 300   # in Sekunden
  radius: 20
  duration: 20    # in Sekunden
supply-drops:
  interval-seconds: 300 # alle 5 Minuten
  radius: 500 # maximaler Abstand von Spawnpunkt

  items:
    NETHER_WART:
      chance: 30
      min: 1
      max: 4

    DIAMOND:
      chance: 20
      min: 3
      max: 10

    GLOWSTONE_DUST:
      chance: 25
      min: 4
      max: 8

    REDSTONE:
      chance: 25
      min: 8
      max: 16

    NETHERITE_barren:
      chance: 10
      min: 1
      max: 3

    NETHERITE_UPGRADE_SMITHING_TEMPLATE:
      chance: 5
      min: 1
      max: 1

