SpeedStorm:
  cooldown: 60
  dragonEggFactor: 0.5
  attackSpeed: 4.0
  speedAmplifier: 3
  duration: 12
Dash:
  cooldown: 5  # Cooldown in Sekunden
Rewind:
  cooldown: 30  # Cooldown in Sekunden
BloodRush:
  cooldown: 60
Stun:
  cooldown: 60
  duration: 3   # in Sekunden
Lightning:
  cooldown: 40       # Sekunden
  duration: 5        # Sekunden aktive Zeit
  range: 10          # Radius um den Spieler
Magma:
  cooldown: 30     # Cooldown in Sekunden für Verdampfen
  radius: 5        # Radius für Wasser-Verdunstung
Healer:
  cooldown: 45   # Cooldown in Sekunden
  radius: 5      # Radius des Heilkreises
  duration: 10   # Dauer der Heilung in Sekunden
emerald:
  cooldown: 100          # Cooldown in Sekunden
  debuff_duration: 5    # Dauer des Verfluchens (in Sekunden)
  fail_chance: 0.3      # 30% Chance dass Items fehlschlagen
infernal_slash:
  cooldown: 20
RapidTripleBowAbility:
  cooldown: 120



